### ISSUE TITLE
Can't use blockinfile more than once for the same file?

### ISSUE THREAD

**Issue by mikeycmccarthy** [yaegashi/ansible-role-blockinfile#7]
I've been trying to use blockinfile twice for the same file and it seems the second insertion takes priority and the first is nowhere to be seen. Intentional or bug? Thanks!

**Comment by mikeycmccarthy** [comment]
It appears that the second blockinfile content turns up in the place where the first content was.

**Comment by yaegashi** [comment]
That seems intended behavior.  It replaces all lines surrounded by the block markers with the specified content.  If you want more than one blocks in a file you can specify different `marker` option for each block.

**Comment by Phyks** [comment]
:+1: but should be documented in the README I think, no?

**Comment by mikeycmccarthy** [comment]
Cool - I figured it might be intended behaviour after a bit. Something in the README would have saved five minutes of thinking I was going mad so that would be a plus one from me too :)

**Comment by yaegashi** [comment]
Updated in v0.5.
